### ISSUE TITLE
Your evaluation perhaps has some problem?

### ISSUE THREAD

**Issue by Guptajakala** [j96w/6-PACK#12]
https://github.com/j96w/6-PACK/blob/cac1b29f3e7a5e9532de610b4f5516919edb0063/dataset/eval_list/eval_list_1.txt#L5
Here the "bottle_shengjun_norm scene_3" appeared twice. That might affect your final result on the bottle category.

**Comment by j96w** [comment]
Hi, please refer to the `benchmark.py` to do the evaluation, and in this code, we didn't use the `eval_list.txt`. The only problem of this duplicate is during the first step of our evaluation, where we use the model to acquire the pose prediction results, the model will test this object twice and the second result will cover the previous one. In the second step, the `benchmark.py` will get a score from the pose prediction results, which won't count the score of this object twice since the first one has already been covered by the second one.

**Comment by Guptajakala** [comment]
This answered
